- name: install neovim
  tags: neovim
- name: clone neovim repo
  tags: neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/personal/neovim"
    single_branch: yes
    version: v0.10.1
- name: install deps
  ansible.builtin.apt:
    pkg: ["cmake", "gettext", "lua5.1", "liblua5.1-0-dev"]
- name: neovim
  make:
    chdir: "{{ lookup('ansible.builtin.env', 'HOME') }}/personal/neovim"
    params:
      CMAKE_BUILD_TYPE: "RelWithDebInfo"
- name: neovim install
  become: true
  make:
    target: install
    chdir: "{{ lookup('ansible.builtin.env', 'HOME') }}/personal/neovim"
