# TODO: so, what is the purpose of such global mise.toml then?
# https://mise.jdx.dev/configuration.html
[tools]
node = 'lts'

# TODO: unused?
[tasks."terraform:check"]
description = "Checks the Terraform files"
depends = ["terraform:format", "terraform:validate"]

[settings]
idiomatic_version_file_enable_tools = ["node"]
