- hosts: localhost
  become: true
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
      tags:
        # - zsh
        - node
        # - tmux
  tasks:
    # - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/node.yml
    # - include_tasks: tasks/tmux.yml
    